import yoklama.modules.dergipark
import yoklama.modules.donanimhaber
import yoklama.modules.eksisozluk
import yoklama.modules.evrimagaci
import yoklama.modules.incisozluk
import yoklama.modules.instela
import yoklama.modules.kizlarsoruyor
import yoklama.modules.memurlarsozluk
import yoklama.modules.onedio
import yoklama.modules.shiftdelete
import yoklama.modules.technopat
import yoklama.modules.teknoseyir
import yoklama.modules.uludagsozluk
